"use client"
import { useState, useEffect } from 'react'
import { createClient } from '@supabase/supabase-js'
function getClient(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL;const k=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!u||!k)return null;return createClient(u,k)}
export default function Admin(){
  const [authed,setAuthed]=useState(false);const [pw,setPw]=useState('');const [posts,setPosts]=useState<any[]>([]);const [editing,setEditing]=useState<any>(null);const [form,setForm]=useState({title:'',category:'Công nghệ',excerpt:'',content:'',read_time:'5 phút',cover_gradient:'from-amber-200 to-orange-300',cover_image:'',is_featured:false});const [layoutMode,setLayoutMode]=useState('magazine')
  useEffect(()=>{if(localStorage.getItem('qv_admin')==='true'){setAuthed(true);load()}},[])
  const load=async()=>{const sb=getClient();if(!sb)return;const {data}=await sb.from('posts').select('*').order('published_at',{ascending:false});if(data)setPosts(data)}
  const login=()=>{if(pw==='quangvuong'){localStorage.setItem('qv_admin','true');setAuthed(true);load()}else alert('Sai')}
  const save=async()=>{const sb=getClient();if(!sb)return;if(!form.title)return alert('Nhap tieu de');if(editing?.id){await sb.from('posts').update(form).eq('id',editing.id)}else{await sb.from('posts').insert([{...form,published_at:new Date().toISOString()}])}setEditing(null);load()}
  const del=async(id:string)=>{if(confirm('Xoa?')){const sb=getClient();if(!sb)return;await sb.from('posts').delete().eq('id',id);load()}}
  const toggleF=async(p:any)=>{const sb=getClient();if(!sb)return;await sb.from('posts').update({is_featured:!p.is_featured}).eq('id',p.id);load()}
  if(!authed)return(<div className="p-8"><input type="password" value={pw} onChange={e=>setPw(e.target.value)}/><button onClick={login}>Login</button></div>)
  return(<div className="min-h-screen bg-[#FFF6E8] p-6"><div className="max-w-[1240px] mx-auto"><div className="flex justify-between"><h1 className="font-serif text-3xl">Admin - {posts.length} bai - {layoutMode}</h1><div className="flex gap-2"><button onClick={()=>setLayoutMode('magazine')} className="px-4 py-2 rounded-full bg-black text-white">Tap chi</button><button onClick={()=>setLayoutMode('grid')} className="px-4 py-2 rounded-full border">Luoi</button><a href="/" className="px-4 py-2 rounded-full border bg-white">Xem trang chu</a></div></div><div className="grid md:grid-cols-3 gap-6 mt-8">{posts.map(p=><div key={p.id} className="bg-white rounded-[28px] p-4 relative"><button onClick={()=>toggleF(p)} className="absolute top-2 right-2">{p.is_featured?'★':'☆'}</button><div className="h-[160px] rounded-[16px] overflow-hidden bg-gray-100">{p.cover_image?<img src={p.cover_image} className="w-full h-full object-cover"/>:<div className={`w-full h-full bg-gradient-to-br ${p.cover_gradient}`}/>}</div><div className="font-serif mt-2">{p.title}</div><div className="flex gap-2 mt-2"><button onClick={()=>{setForm(p);setEditing(p)}} className="px-3 py-1 border rounded-full">Sua</button><button onClick={()=>del(p.id)} className="px-3 py-1 bg-red-500 text-white rounded-full">Xoa</button></div></div>)}</div></div>
  {editing && <div className="fixed inset-0 bg-black/40 flex items-center justify-center p-4"><div className="bg-white rounded-[24px] p-6 w-full max-w-lg"><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Tieu de" className="w-full border p-2 mb-2"/><input value={form.cover_image} onChange={e=>setForm({...form,cover_image:e.target.value})} placeholder="Link anh cover" className="w-full border p-2 mb-2"/><textarea value={form.excerpt} onChange={e=>setForm({...form,excerpt:e.target.value})} placeholder="Mo ta" className="w-full border p-2 mb-2"/><button onClick={save} className="w-full bg-black text-white rounded-full py-2">Luu</button><button onClick={()=>setEditing(null)} className="w-full mt-2 border rounded-full py-2">Huy</button></div></div>}
  </div>)
}
