"use client"
import { useState, useEffect } from 'react'
import { createClient } from '@supabase/supabase-js'
function getClient(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL;const k=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!u||!k)return null;return createClient(u,k)}
type Post={id:string;title:string;category:string;excerpt:string;content:string;cover_gradient:string;cover_image?:string;read_time:string;is_featured?:boolean}
export default function Admin(){
  const [authed,setAuthed]=useState(false);const [pw,setPw]=useState('');const [posts,setPosts]=useState<Post[]>([]);const [editing,setEditing]=useState<Post|null>(null);const [form,setForm]=useState({title:'',category:'Công nghệ',excerpt:'',content:'',read_time:'5 phút',cover_gradient:'from-amber-200 to-orange-300',cover_image:'',is_featured:false});const [uploading,setUploading]=useState(false)
  useEffect(()=>{if(localStorage.getItem('qv_admin')==='true'){setAuthed(true);load()}},[])
  const load=async()=>{const sb=getClient();if(!sb)return;const {data}=await sb.from('posts').select('*').order('published_at',{ascending:false});if(data)setPosts(data as Post[])}
  const login=()=>{if(pw==='quangvuong'){localStorage.setItem('qv_admin','true');setAuthed(true);load()}else alert('Sai mk')}
  const handleFile=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;setUploading(true);try{const sb=getClient();if(sb){const name=`${Date.now()}-${file.name}`;const {error}=await sb.storage.from('covers').upload(name,file);if(!error){const {data}=sb.storage.from('covers').getPublicUrl(name);setForm({...form,cover_image:data.publicUrl});setUploading(false);return}}const r=new FileReader();r.onload=()=>{setForm(f=>({...f,cover_image:r.result as string}));setUploading(false)};r.readAsDataURL(file)}catch{setUploading(false)}}
  const openNew=()=>{setForm({title:'',category:'Công nghệ',excerpt:'',content:'',read_time:'5 phút',cover_gradient:'from-amber-200 to-orange-300',cover_image:'',is_featured:false});setEditing({id:'',title:'',category:'',excerpt:'',content:'',cover_gradient:'',cover_image:'',read_time:''} as any)}
  const openEdit=(p:Post)=>{setForm({title:p.title,category:p.category,excerpt:p.excerpt,content:p.content||'',read_time:p.read_time,cover_gradient:p.cover_gradient||'from-amber-200 to-orange-300',cover_image:p.cover_image||'',is_featured:!!p.is_featured});setEditing(p)}
  const save=async()=>{const sb=getClient();if(!sb)return alert('Chưa có ENV');if(!form.title)return alert('Nhập tiêu đề');if(editing && editing.id){await sb.from('posts').update({...form}).eq('id',editing.id);if(form.is_featured){for(const p of posts){if(p.id!==editing.id && p.is_featured){await sb.from('posts').update({is_featured:false}).eq('id',p.id)}}}}else{await sb.from('posts').insert([{...form,published_at:new Date().toISOString()}])}setEditing(null);load()}
  const del=async(id:string)=>{if(!confirm('Xóa?'))return;const sb=getClient();if(!sb)return;await sb.from('posts').delete().eq('id',id);load()}
  const toggleF=async(p:Post)=>{const sb=getClient();if(!sb)return;const nv=!p.is_featured;if(nv){for(const o of posts){if(o.id!==p.id && o.is_featured){await sb.from('posts').update({is_featured:false}).eq('id',o.id)}} }await sb.from('posts').update({is_featured:nv}).eq('id',p.id);load()}
  if(!authed)return(<div className="min-h-screen flex items-center justify-center bg-[#FFF6E8] p-6"><div className="bg-white rounded-[28px] p-10 w-full max-w-sm shadow"><h1 className="font-serif text-3xl mb-6">Admin</h1><input type="password" value={pw} onChange={e=>setPw(e.target.value)} placeholder="Mật khẩu" className="w-full border rounded-full px-5 py-3 mb-4"/><button onClick={login} className="w-full bg-black text-white rounded-full py-3">Đăng nhập</button></div></div>)
  const featured=posts.find(p=>p.is_featured)||posts[0];const rest=posts.filter(p=>p.id!==featured?.id)
  return(
    <main className="min-h-screen bg-[#FFF6E8] p-6">
      <div className="max-w-[1240px] mx-auto flex justify-between items-center mb-8"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-full bg-black text-white flex items-center justify-center font-bold">QV</div><div><div className="font-serif text-xl font-semibold">Quang Vương • Admin</div><div className="text-[11px] opacity-60 uppercase">Bấm vào card để sửa • {posts.length} bài</div></div></div><div className="flex gap-2"><a href="/" className="border rounded-full px-4 py-2 bg-white text-sm">Xem trang chủ</a><button onClick={()=>{localStorage.removeItem('qv_admin');setAuthed(false)}} className="text-sm opacity-60">Đăng xuất</button></div></div>
      <div className="max-w-[1240px] mx-auto flex justify-between items-center mb-6"><h1 className="font-serif text-3xl">Chỉnh bố cục — bấm vào card để sửa</h1><button onClick={openNew} className="bg-black text-white rounded-full px-6 py-3 text-sm">+ Thêm bài mới</button></div>
      <div className="max-w-[1240px] mx-auto grid md:grid-cols-3 gap-8">
        {featured && (
          <div onClick={()=>openEdit(featured)} className="md:col-span-2 bg-white rounded-[32px] p-3 shadow cursor-pointer hover:shadow-xl transition-all relative group">
            <div className="absolute top-5 right-5 flex gap-2 z-10"><button onClick={(e)=>{e.stopPropagation(); toggleF(featured)}} className={`w-9 h-9 rounded-full ${featured.is_featured?'bg-yellow-400':'bg-white border'}`}>★</button><button onClick={(e)=>{e.stopPropagation(); del(featured.id)}} className="w-9 h-9 rounded-full bg-red-500 text-white">✕</button></div>
            <div className="h-[380px] rounded-[24px] overflow-hidden bg-gradient-to-br from-amber-200 to-orange-300">{featured.cover_image?<img src={featured.cover_image} className="w-full h-full object-cover"/>:null}</div>
            <div className="p-4"><div className="text-[11px] uppercase opacity-60">FEATURED • {featured.category}</div><div className="font-serif text-2xl mt-2">{featured.title}</div><div className="text-sm opacity-60 mt-1">{featured.excerpt}</div><div className="mt-3 text-sm text-blue-600">→ Bấm để sửa</div></div>
          </div>
        )}
        <div className="flex flex-col gap-6"><button onClick={openNew} className="bg-white/60 border-2 border-dashed rounded-[28px] h-[160px]">+ Thêm bài mới</button>{rest.slice(0,2).map(p=>(<div key={p.id} onClick={()=>openEdit(p)} className="bg-white rounded-[28px] p-4 shadow cursor-pointer hover:shadow-lg"><div className="h-[130px] rounded-[16px] bg-gray-100 overflow-hidden">{p.cover_image?<img src={p.cover_image} className="w-full h-full object-cover"/>:<div className={`w-full h-full bg-gradient-to-br ${p.cover_gradient}`}/>}</div><div className="font-serif mt-2">{p.title}</div></div>))}</div>
        {rest.slice(2).map(p=>(<div key={p.id} onClick={()=>openEdit(p)} className="bg-white rounded-[28px] p-5 shadow cursor-pointer hover:shadow-lg"><div className="h-[180px] rounded-[20px] bg-gray-100 overflow-hidden">{p.cover_image?<img src={p.cover_image} className="w-full h-full object-cover"/>:<div className={`w-full h-full bg-gradient-to-br ${p.cover_gradient}`}/>}</div><div className="font-serif mt-3">{p.title}</div></div>))}
      </div>
      {editing && (<div className="fixed inset-0 bg-black/40 flex items-center justify-center p-4 z-50"><div className="bg-white rounded-[24px] p-6 w-full max-w-lg max-h-[90vh] overflow-auto"><h2 className="font-serif text-2xl mb-4">{editing.id?'Sửa bài':'Bài mới'}</h2><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Tiêu đề" className="w-full border rounded-xl p-3 mb-2"/><input value={form.excerpt} onChange={e=>setForm({...form,excerpt:e.target.value})} placeholder="Mô tả" className="w-full border rounded-xl p-3 mb-2"/><textarea value={form.content} onChange={e=>setForm({...form,content:e.target.value})} placeholder="Nội dung" rows={4} className="w-full border rounded-xl p-3 mb-2"/><div className="flex gap-2 mb-2"><input value={form.cover_image} onChange={e=>setForm({...form,cover_image:e.target.value})} placeholder="Link ảnh" className="flex-1 border rounded-xl p-3"/><label className="px-4 py-3 bg-black text-white rounded-xl text-sm cursor-pointer">{uploading?'...':'Upload'}<input type="file" accept="image/*" className="hidden" onChange={handleFile}/></label></div>{form.cover_image && <img src={form.cover_image} className="rounded-xl mb-3 max-h-[200px] w-full object-cover"/>}<label className="flex gap-2 mb-4 text-sm"><input type="checkbox" checked={form.is_featured} onChange={e=>setForm({...form,is_featured:e.target.checked})}/> Ghim Featured</label><button onClick={save} className="w-full bg-black text-white rounded-full py-3">Lưu</button><button onClick={()=>setEditing(null)} className="w-full border rounded-full py-3 mt-2">Hủy</button></div></div>)}
    </main>
  )
}
