"use client"
import { useState, useEffect } from 'react'
import { createClient } from '@supabase/supabase-js'
function getClient(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL;const k=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!u||!k)return null;return createClient(u,k)}
type Post={id:string;title:string;category:string;excerpt:string;content:string;cover_gradient:string;cover_image?:string;read_time:string;is_featured?:boolean}
type Settings={badge_text:string;hero_line1:string;hero_line2:string;hero_desc:string;location_text:string;site_name:string}
export default function Admin(){
  const [authed,setAuthed]=useState(false);const [pw,setPw]=useState('');const [posts,setPosts]=useState<Post[]>([]);const [editing,setEditing]=useState<Post|null>(null);const [form,setForm]=useState({title:'',category:'Công nghệ',excerpt:'',content:'',read_time:'5 phút',cover_gradient:'from-amber-200 to-orange-300',cover_image:'',is_featured:false});const [settings,setSettings]=useState<Settings>({badge_text:'Đang sống chậm tại Đức Nội',hero_line1:'Sống chậm,',hero_line2:'làm kỹ.',hero_desc:'Góc nhỏ ghi lại hành trình tối giản, làm việc sâu và xây hệ thống ghi chú cho người lười nhưng muốn hiệu quả.',location_text:'ĐỨC NỘI • HÀ NỘI • 2026',site_name:'Quang Vương'});const [showSettings,setShowSettings]=useState(false);const [uploading,setUploading]=useState(false);const [preview,setPreview]=useState('')
  useEffect(()=>{if(localStorage.getItem('qv_admin')==='true'){setAuthed(true);load(); loadSettings()}},[])
  const load=async()=>{const sb=getClient();if(!sb)return;const {data}=await sb.from('posts').select('*').order('published_at',{ascending:false});if(data)setPosts(data as Post[])}
  const loadSettings=async()=>{const sb=getClient();if(!sb)return;const {data}=await sb.from('site_settings').select('*').eq('id',1).single();if(data)setSettings({badge_text:data.badge_text,hero_line1:data.hero_line1,hero_line2:data.hero_line2,hero_desc:data.hero_desc,location_text:data.location_text,site_name:data.site_name})}
  const login=()=>{if(pw==='quangvuong'){localStorage.setItem('qv_admin','true');setAuthed(true);load();loadSettings()}else alert('Sai mk')}
  const handleFile=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const b64=reader.result as string;setPreview(b64);setForm(f=>({...f,cover_image:b64}))};reader.readAsDataURL(file);setUploading(true);try{const sb=getClient();if(sb){const name=`${Date.now()}-${file.name}`;const {error}=await sb.storage.from('covers').upload(name,file,{upsert:true});if(!error){const {data}=sb.storage.from('covers').getPublicUrl(name);if(data?.publicUrl){setForm(f=>({...f,cover_image:data.publicUrl}));setPreview(data.publicUrl)}}}}catch{}setUploading(false)}
  const openNew=()=>{setForm({title:'',category:'Công nghệ',excerpt:'',content:'',read_time:'5 phút',cover_gradient:'from-amber-200 to-orange-300',cover_image:'',is_featured:false});setPreview('');setEditing({id:'',title:'',category:'',excerpt:'',content:'',cover_gradient:'',cover_image:'',read_time:''} as any)}
  const openEdit=(p:Post)=>{setForm({title:p.title,category:p.category,excerpt:p.excerpt,content:p.content||'',read_time:p.read_time,cover_gradient:p.cover_gradient||'from-amber-200 to-orange-300',cover_image:p.cover_image||'',is_featured:!!p.is_featured});setPreview(p.cover_image||'');setEditing(p)}
  const save=async()=>{const sb=getClient();if(!sb)return;if(!form.title)return alert('Nhap tieu de');if(editing&&editing.id){await sb.from('posts').update({...form}).eq('id',editing.id)}else{await sb.from('posts').insert([{...form,published_at:new Date().toISOString()}])}setEditing(null);setPreview('');load()}
  const saveSettings=async()=>{const sb=getClient();if(!sb)return alert('Chua co ENV');await sb.from('site_settings').upsert({id:1,...settings});alert('Đã lưu trang chủ!');setShowSettings(false)}
  const del=async(id:string)=>{if(!confirm('Xoa?'))return;const sb=getClient();if(!sb)return;await sb.from('posts').delete().eq('id',id);load()}
  if(!authed)return(<div className="min-h-screen flex items-center justify-center bg-[#FFF6E8] p-6"><div className="bg-white rounded-[28px] p-10 w-full max-w-sm shadow"><h1 className="text-3xl font-bold mb-6">Admin</h1><input type="password" value={pw} onChange={e=>setPw(e.target.value)} placeholder="Mat khau" className="w-full border rounded-full px-5 py-3 mb-4"/><button onClick={login} className="w-full bg-black text-white rounded-full py-3">Dang nhap</button></div></div>)
  return(
    <main className="min-h-screen bg-[#FFF6E8] p-6">
      <div className="max-w-[1240px] mx-auto flex justify-between items-center mb-8"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-full bg-black text-white flex items-center justify-center font-bold">QV</div><div><div className="font-bold text-xl">Quang Vương • Admin</div><div className="text-[11px] opacity-60 uppercase">Chỉnh được cả trang chủ</div></div></div><div className="flex gap-2"><button onClick={()=>setShowSettings(true)} className="bg-black text-white rounded-full px-4 py-2 text-sm">Chỉnh trang chủ</button><a href="/" className="border rounded-full px-4 py-2 bg-white text-sm">Xem trang chủ</a></div></div>
      <div className="max-w-[1240px] mx-auto mb-6 p-4 bg-white rounded-[20px] shadow-sm"><div className="text-[11px] uppercase opacity-60">Xem trước trang chủ</div><div className="mt-2 flex gap-2 items-center"><span className="px-3 py-1 bg-[#FFF6E8] rounded-full text-xs">{settings.badge_text} • {posts.length} bài</span><span className="text-xs opacity-60">{settings.location_text}</span></div><div className="font-bold text-2xl mt-2">{settings.hero_line1} {settings.hero_line2}</div><div className="text-sm opacity-70 mt-1">{settings.hero_desc}</div><button onClick={()=>setShowSettings(true)} className="mt-3 text-sm text-blue-600">→ Bấm để chỉnh phần này</button></div>
      <div className="max-w-[1240px] mx-auto flex justify-between items-center mb-6"><h1 className="font-bold text-2xl">Bài viết • bấm vào card để sửa</h1><button onClick={openNew} className="bg-black text-white rounded-full px-6 py-3 text-sm">+ Thêm bài mới</button></div>
      <div className="max-w-[1240px] mx-auto grid md:grid-cols-3 gap-6">
        {posts.map(p=>(<div key={p.id} onClick={()=>openEdit(p)} className="bg-white rounded-[28px] p-4 shadow cursor-pointer"><div className="h-[160px] rounded-[16px] bg-gray-100 overflow-hidden">{p.cover_image?<img src={p.cover_image} className="w-full h-full object-cover"/>:<div className={`w-full h-full bg-gradient-to-br ${p.cover_gradient}`}/>}</div><div className="font-bold mt-2">{p.title}</div><div className="text-xs opacity-60">{p.category}</div></div>))}
      </div>
      {editing && (<div className="fixed inset-0 bg-black/40 flex items-center justify-center p-4 z-50"><div className="bg-white rounded-[24px] p-6 w-full max-w-lg max-h-[90vh] overflow-auto"><h2 className="font-bold text-2xl mb-4">{editing.id?'Sửa bài':'Bài mới'}</h2><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Tiêu đề" className="w-full border rounded-xl p-3 mb-2"/><input value={form.excerpt} onChange={e=>setForm({...form,excerpt:e.target.value})} placeholder="Mô tả" className="w-full border rounded-xl p-3 mb-2"/><div className="flex gap-2 mb-2"><input value={form.cover_image} onChange={e=>{setForm({...form,cover_image:e.target.value});setPreview(e.target.value)}} placeholder="Link ảnh" className="flex-1 border rounded-xl p-3"/><label className="px-4 py-3 bg-black text-white rounded-xl text-sm cursor-pointer">{uploading?'...':'Upload'}<input type="file" accept="image/*" className="hidden" onChange={handleFile}/></label></div>{(preview||form.cover_image)&&<img src={preview||form.cover_image} className="rounded-xl mb-3 max-h-[200px] w-full object-cover"/>}<button onClick={save} className="w-full bg-black text-white rounded-full py-3">Lưu</button><button onClick={()=>{setEditing(null);setPreview('')}} className="w-full border rounded-full py-3 mt-2">Hủy</button></div></div>)}
      {showSettings && (
        <div className="fixed inset-0 bg-black/40 backdrop-blur-sm flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-[24px] p-6 w-full max-w-xl max-h-[90vh] overflow-auto">
            <h2 className="font-bold text-2xl mb-1">Chỉnh phần đầu trang</h2><p className="text-sm opacity-60 mb-6">Chính là phần bạn khoanh trong ảnh</p>
            <label className="text-sm font-medium">Tên site (góc trái)</label><input value={settings.site_name} onChange={e=>setSettings({...settings,site_name:e.target.value})} className="w-full border rounded-xl p-3 mb-3 mt-1"/>
            <label className="text-sm font-medium">Dòng địa điểm (ĐỨC NỘI • HÀ NỘI • 2026)</label><input value={settings.location_text} onChange={e=>setSettings({...settings,location_text:e.target.value})} className="w-full border rounded-xl p-3 mb-3 mt-1"/>
            <label className="text-sm font-medium">Badge xanh (Đang sống chậm...)</label><input value={settings.badge_text} onChange={e=>setSettings({...settings,badge_text:e.target.value})} className="w-full border rounded-xl p-3 mb-3 mt-1"/>
            <label className="text-sm font-medium">Tiêu đề dòng 1 (Sống chậm,)</label><input value={settings.hero_line1} onChange={e=>setSettings({...settings,hero_line1:e.target.value})} className="w-full border rounded-xl p-3 mb-3 mt-1"/>
            <label className="text-sm font-medium">Tiêu đề dòng 2 (làm kỹ.)</label><input value={settings.hero_line2} onChange={e=>setSettings({...settings,hero_line2:e.target.value})} className="w-full border rounded-xl p-3 mb-3 mt-1"/>
            <label className="text-sm font-medium">Mô tả dưới tiêu đề</label><textarea value={settings.hero_desc} onChange={e=>setSettings({...settings,hero_desc:e.target.value})} rows={3} className="w-full border rounded-xl p-3 mb-6 mt-1"/>
            <div className="flex gap-3"><button onClick={saveSettings} className="flex-1 bg-black text-white rounded-full py-3">Lưu trang chủ</button><button onClick={()=>setShowSettings(false)} className="px-6 border rounded-full">Hủy</button></div>
          </div>
        </div>
      )}
    </main>
  )
}
